apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-bootstrap
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: bootstrap
          image: hashicorp/vault:1.21.2
          env:
            - {name: VAULT_ADDR,  value: "http://vault:8200"}
            - {name: VAULT_TOKEN, value: "root"}
          command: ["/bin/sh", "-ec"]
          args:
            - |
              vault kv put secret/app SYS_ENV=hello-enclaive

              vault auth enable kubernetes || true
              vault write auth/kubernetes/config kubernetes_host=https://kubernetes.default.svc

              vault policy write app - <<'EOF'
              path "secret/data/app" {
                capabilities = ["read"]
              }
              EOF

              vault write auth/kubernetes/role/app \
                bound_service_account_names=app \
                bound_service_account_namespaces=dev,prod \
                policies=app
